# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# Fix the import path
from src import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationServiceStub(object):
    """The replication service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/replication.ReplicationService/Heartbeat',
                request_serializer=replication__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=replication__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.StoreMessage = channel.unary_unary(
                '/replication.ReplicationService/StoreMessage',
                request_serializer=replication__pb2.StoreRequest.SerializeToString,
                response_deserializer=replication__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/replication.ReplicationService/GetMessage',
                request_serializer=replication__pb2.GetRequest.SerializeToString,
                response_deserializer=replication__pb2.GetResponse.FromString,
                _registered_method=True)
        self.RequestMessageSteal = channel.unary_unary(
                '/replication.ReplicationService/RequestMessageSteal',
                request_serializer=replication__pb2.StealRequest.SerializeToString,
                response_deserializer=replication__pb2.StealResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/replication.ReplicationService/GetMetrics',
                request_serializer=replication__pb2.MetricsRequest.SerializeToString,
                response_deserializer=replication__pb2.MetricsResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """The replication service definition.
    """

    def Heartbeat(self, request, context):
        """Health check service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMessage(self, request, context):
        """Store a message with replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Retrieve a message from the system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMessageSteal(self, request, context):
        """Request to steal messages for load balancing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Get system metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=replication__pb2.HeartbeatRequest.FromString,
                    response_serializer=replication__pb2.HeartbeatResponse.SerializeToString,
            ),
            'StoreMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMessage,
                    request_deserializer=replication__pb2.StoreRequest.FromString,
                    response_serializer=replication__pb2.StoreResponse.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=replication__pb2.GetRequest.FromString,
                    response_serializer=replication__pb2.GetResponse.SerializeToString,
            ),
            'RequestMessageSteal': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMessageSteal,
                    request_deserializer=replication__pb2.StealRequest.FromString,
                    response_serializer=replication__pb2.StealResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=replication__pb2.MetricsRequest.FromString,
                    response_serializer=replication__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """The replication service definition.
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/Heartbeat',
            replication__pb2.HeartbeatRequest.SerializeToString,
            replication__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/StoreMessage',
            replication__pb2.StoreRequest.SerializeToString,
            replication__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/GetMessage',
            replication__pb2.GetRequest.SerializeToString,
            replication__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMessageSteal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/RequestMessageSteal',
            replication__pb2.StealRequest.SerializeToString,
            replication__pb2.StealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/GetMetrics',
            replication__pb2.MetricsRequest.SerializeToString,
            replication__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
